##
# 02 - Project Euler
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.max = 4000000

def fibonacci_seq(max)
  first = 1
  second = 2
  sum = 2 # accounts for the first fibonacci pair
  while((first + second) < max)
    third = first + second
    first = second
    second = third
    sum += third if third.even?
  end
  puts sum
end

fibonacci_seq(max)
